FROM tensorflow/serving

ENV MODEL_NAME=bert

RUN mkdir /models/bert

COPY ./bert_model/ /models/bert/

EXPOSE 8501

CMD tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=bert --model_base_path=/models/bert